candidateProfile:
    daxtraUsername: ENC[AES256_GCM,data:IcBpnU4nUQ==,iv:i9leXpQvIDN6IRcvpZdWzbU49LOO22Hm8dwz2fyYdo4=,tag:jddqpcgPhBNPnCnwqiQ31Q==,type:str]
    daxtraPassword: ENC[AES256_GCM,data:tJNqlLsV2w==,iv:KUrZlICLH7EmTQYdVQf+eYFfkRlwWt4A09dQ8FnsxWc=,tag:o/Hm8IUD8O1EiCS6FO0ADA==,type:str]
    phoenixUsername: ENC[AES256_GCM,data:hvhIxBdQ2A==,iv:LZAQ+G5V2TkMM0vxbcjQlKwTmlEyiUE1jS9BzILwW3I=,tag:hZw5LTKjWiMMnm6KC7fBlw==,type:str]
    phoenixPassword: ENC[AES256_GCM,data:VFK3AfN2kg==,iv:kUBjCzwo26zaRAb3L2Vfz9jmQaWEgmNHKco3sMfdXEo=,tag:k//Jo6EAQ7Y/t3F3JLl6Ag==,type:str]
broadbean:
    username: ENC[AES256_GCM,data:RPxXn1PIHw==,iv:rTHmmDkBn48GUsz4+kQBAjRns3aynDfqu6t6cri71Xw=,tag:aGYXaAgeBSVIBxK5ij7QHg==,type:str]
    password: ENC[AES256_GCM,data:fUm0KrJy8gb6T9HUZfnpAV0pw3h3JpV6DUlFg80k,iv:kHEic4zs7V6mATAO3sZvM0trI7DcSsS+d8y2NfH/U7I=,tag:xnVKqIgDnvaJApmuqcoxKw==,type:str]
mandrillCredentials:
    mandrillApiKey: ENC[AES256_GCM,data:3qCcfjaOgQ==,iv:IwIIAU0lFhHSIn+DayuxFWVoIMMbMjJvU5rK5fSL17Q=,tag:ExR6d9fEq3xuQYT64ihnPA==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:eu-west-2:144908211154:key/cc3f7343-31a4-43c7-9c1d-728aec28ff99
        created_at: '2020-09-16T09:24:12Z'
        enc: AQICAHgZTq+J6xYgoJ4P3PATMIYn7GS5G3XbvdL7gXGdZKmq/wFK9FkNf4tHKisWXFlNhyYVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM96qKeCA7d5nivKV+AgEQgDuyVcNoUgE+1CWGK4lZDbemDIHEXBJoUrKNyI2/XBfFRl02E2lyNQirmHCvAXMrVrKnEnYDSREh4bJzXg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-10-02T12:59:43Z'
    mac: ENC[AES256_GCM,data:2jah1buBaPnwCdwpliNwh6fulyviyvjxoRjBCPLgXzl0znfiyosRYf7mP4ehyoF3rRhbLflsbkLR4mI+RHIKe04NpG2aQVI3p7buBd56IuzTM4fmgWGe7tmoPFzET1DGzOvxYrQmf5Wx0J6BNQpyhTYBflkTLnRcPcVBgR2twME=,iv:rP1Tx8erFevlKaGoE7ONaolgyAqfCx7fVqDCsjqGM1s=,tag:ACEKgzg4nd4p0P9EQwL5SA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
