candidateProfile:
    daxtraUsername: ENC[AES256_GCM,data:JkwIxSgkwqhypHBscBs=,iv:ZIUZzyEFtBsYST5KSM2M5TMl5Yg3+27RUZQy9njcLyw=,tag:YU8jXY64cUiIrmAcmOWk9Q==,type:str]
    daxtraPassword: ""
    phoenixUsername: ENC[AES256_GCM,data:lCUaQXxdaJm7ic7lsUgGayAZyLU+ahly4Kc=,iv:gEVvELiNIjj+giYtSxZf3j7TrtyowOPHg77UALUI6j0=,tag:IUMMSx3La24yttfXZBZQEQ==,type:str]
    phoenixPassword: ENC[AES256_GCM,data:0lSn52YNyXm8hZLj,iv:2cszshR4sjQDqEb13uArkic31oAw/gDc0ZHiYS6ZGMU=,tag:ErsrkvSXA7UMJdievzMQyQ==,type:str]
broadbean:
    username: ENC[AES256_GCM,data:cSrYUpBz8CNg,iv:zMcnGA4NELRzysP17+BukH2AuM0EvXzsEr+bs/dceAs=,tag:JKKAVW2/ES6qWtNKbyu6mQ==,type:str]
    password: ENC[AES256_GCM,data:oXGrC3aehtExGvKG0nr/W9xXb3E=,iv:65u8A5sgaZiDFqkOAlM4CespNhQMfggubzsIak3UY0I=,tag:RIxM+/0XnBIGYDyQBeYIeg==,type:str]
mandrillCredentials:
    mandrillApiKey: ENC[AES256_GCM,data:eDhzCZyegP9bnl6KQ24P0jKwj3iZog==,iv:k3yStxWVojJNFavDGiwCSz5hiYXVXfy1YRLjW4q01X8=,tag:QrCZ7HLhC1CyYk5ahNghMg==,type:str]
linkSiteVisitorToPardotAccountCredentials:
    clientId: ENC[AES256_GCM,data:nu4ng9fbBnKDaVcP/1ZOJpX6QnKcCnEECNFmIMBrt0FaMjtEGisFoCkp7wisxy++hHDOjOtAiOTWKb1km+vD+s1KTvR6SkEQD4kQ1xgjVGfdr5NjsA==,iv:mFqmfUTUwdFA01jZOvvj9Z5elZXkSgbAcxRGYFBTWDM=,tag:PfFwx7bEp36IMEBXUVewfA==,type:str]
    userKey: ENC[AES256_GCM,data:cOFai/SzHJdkUvhJ4H2ECAMW3ydn5+ZwF6Ao,iv:6CqOgTcz8OfrJ7sf81I4PoBBDOzduN5+1S4yxJTQP88=,tag:QxSoHUOSueb/9RafHrRBEA==,type:str]
    clientSecret: ENC[AES256_GCM,data:pb5ICnDcFmgSmjtpc7JS7CUT6a+HI3F9jtxMu1aGCsbPN555uRYFNHbHAi48XtWHmm7Quo847YkKvv6OTHR43A==,iv:fJW7Uz//7Nm9xDr8bLv28EQs+kxrnHhT+kzDIm3cYGM=,tag:JWYGkBIxfW03yWGAtYbyQQ==,type:str]
    password: ENC[AES256_GCM,data:RTtW9FfUqMGj0OKn5q3mzNX+LReznbsI8AXD076o066GhOUnGSyM,iv:RapUx8E/XoaEHQZraQUVe9xqn/51cLrCU8gUOgjAFJE=,tag:ugUKQHK7CqRfMDA8dnhsYA==,type:str]
    pardotBusinessUnitId: ENC[AES256_GCM,data:kaHkIDsxaPfzpXqi7JBfX+0a,iv:UpfgdiIOsCFyiFE30mIVI8sn0zUzKJCDiZ+edc0QIV4=,tag:PytdKsXJ/rB2qMxIaMDoYg==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:eu-west-2:144908211154:key/cc3f7343-31a4-43c7-9c1d-728aec28ff99
        created_at: '2020-09-16T09:24:12Z'
        enc: AQICAHgZTq+J6xYgoJ4P3PATMIYn7GS5G3XbvdL7gXGdZKmq/wFK9FkNf4tHKisWXFlNhyYVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM96qKeCA7d5nivKV+AgEQgDuyVcNoUgE+1CWGK4lZDbemDIHEXBJoUrKNyI2/XBfFRl02E2lyNQirmHCvAXMrVrKnEnYDSREh4bJzXg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-10-17T10:32:40Z'
    mac: ENC[AES256_GCM,data:ZqOnsAJHSDgzjD5J5Hu+MXkNhCTRc1vDx7PiEhlj7RHwvj6d8525MpKmBnh1XPsMSLAoxBQDNd2IvwwIC2Xg3voZIQnpbs1eo1SrOKNOWazDZ84k+16me8caFMwMxckoydJZss7R7OsazKJKtwZVNcv+pg6minJ5OLpeavRWrkc=,iv:hrHUn2HoEqXN5CoOrHFPdz0E7yGz8Fv3hp7hCKpey9s=,tag:Bq84dOcDwdPxqTj08Aq/1w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
